### ISSUE TITLE
Exception in thread "specs2.user-1" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by hepin1989** [scalaz/scalaz-zio#407]
```
Exception in thread "specs2.user-1" java.lang.StackOverflowError
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
	at scalaz.zio.IO.$anonfun$map$1(IO.scala:57)
```

**Comment by jdegoes** [comment]
Be sure to use `sbt` script from inside the repository to run the tests, because it has adequate stack size for all the examples.

**Comment by kaishh** [comment]
Why not add a `.jvmopts` file with a -ss option?

**Comment by jdegoes** [comment]
PRs welcome. 😄

**Comment by joriscode** [comment]
I will do it as soon as I get a better internet connection (soon)!
