### ISSUE TITLE
AbstractMethodError with zio 0.5.+

### ISSUE THREAD

**Issue by TheDIM47** [scalaz/scalaz-zio#437]
After upgrading to zio 0.5.+ i'm starting to get AbstractMethodError
doobie v0.6.0. scala 2.12.7/2.12.8
zio v0.3.+ and v0.4.+ works fine.

Minimal sample:
```
package test

import doobie.util.transactor.Transactor
import org.scalatest.{FreeSpec, Matchers}
import scalaz.zio.RTS

class SimpleSpec extends FreeSpec with Matchers with RTS {
  import scalaz.zio.interop.Task
  import scalaz.zio.interop.catz._
  import scalaz.zio.console._

  implicit val xa: Transactor[Task] = Transactor.fromDriverManager[Task](
    "driver","url","username","password"
  )

  "test" in {
    for {
      _ <- putStrLn("Hello! What is your name?")
    } yield ()
  }

}
```

```
An exception or error caused a run to abort: Method scalaz/zio/interop/CatsConcurrent.scalaz$zio$RTS$_setter_$executionContext_$eq(Lscala/concurrent/ExecutionContext;)V is abstract 
java.lang.AbstractMethodError: Method scalaz/zio/interop/CatsConcurrent.scalaz$zio$RTS$_setter_$executionContext_$eq(Lscala/concurrent/ExecutionContext;)V is abstract
	at scalaz.zio.interop.CatsConcurrent.scalaz$zio$RTS$_setter_$executionContext_$eq(catsjvm.scala)
	at scalaz.zio.RTS.$init$(RTS.scala:69)
	at scalaz.zio.interop.CatsEffect.<init>(catsjvm.scala:99)
	at scalaz.zio.interop.CatsConcurrent.<init>(catsjvm.scala:56)
	at scalaz.zio.interop.CatsInstances.<init>(catsjvm.scala:37)
	at scalaz.zio.interop.CatsPlatform.<init>(catsjvm.scala:10)
	at scalaz.zio.interop.catz$.<init>(cats.scala:3)
	at scalaz.zio.interop.catz$.<clinit>(cats.scala)
	at test.SimpleSpec.<init>(SimpleSpec.scala:12)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1428)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1236)
	at scala.collection.immutable.List.map(List.scala:286)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1235)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by ghostdogpr** [comment]
Hmm strange, your sample works for me in a brand new project.
Did you upgrade the `interop` dependency as well?
```
"org.scalaz"    %% "scalaz-zio"         % "0.5.0",
"org.scalaz"    %% "scalaz-zio-interop" % "0.5.0"
```

**Comment by TheDIM47** [comment]
> Did you upgrade the `interop` dependency as well?
Yes. I have "interop" dependency. I'll try to play with compiler options. Thanks!
