### ISSUE TITLE
Failure to deploy release

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#479]
```
[error] Multiple repositories are found:
[error] [orgscalaz-1302] status:open, profile:org.scalaz(12f2db3889b6a) description: Implicitly created (auto staging).
[error] [orgscalaz-1304] status:open, profile:org.scalaz(12f2db3889b6a) description: Implicitly created (auto staging).
[error] [orgscalaz-1305] status:open, profile:org.scalaz(12f2db3889b6a) description: Implicitly created (auto staging).
[error] [orgscalaz-1306] status:open, profile:org.scalaz(12f2db3889b6a) description: Implicitly created (auto staging).
[error] [orgscalaz-1307] status:open, profile:org.scalaz(12f2db3889b6a) description: Implicitly created (auto staging).
[error] [orgscalaz-1308] status:open, profile:org.scalaz(12f2db3889b6a) description: Implicitly created (auto staging).
[error] Specify one of the repository ids in the command line
[error] java.lang.IllegalStateException: Found multiple staging repositories
[error] 	at xerial.sbt.Sonatype$NexusRESTService.$anonfun$findTargetRepository$8(Sonatype.scala:532)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.findTargetRepository(Sonatype.scala:529)
[error] 	at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeRelease$1(Sonatype.scala:269)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalStateException: Found multiple staging repositories
[error] Use 'last' for the full log.
```

```
[error] Failed to close the repository
[error] Activity close started:2018-12-20T02:23:36.372Z, stopped:2018-12-20T02:24:01.131Z
[error]     Failed: checksum-staging, failureMessage:Missing MD5: '/org/scalaz/scalaz-zio_sjs0.6_2.12/0.5.1/scalaz-zio_sjs0.6_2.12-0.5.1-javadoc.jar.md5'
[error]     Failed: signature-staging, failureMessage:Missing Signature: '/org/scalaz/scalaz-zio_sjs0.6_2.12/0.5.1/scalaz-zio_sjs0.6_2.12-0.5.1-javadoc.jar.asc' does not exist for 'scalaz-zio_sjs0.6_2.12-0.5.1-javadoc.jar'.
[error]     Failed: sources-staging, failureMessage:Missing: no main jar artifact found in folder '/org/scalaz/scalaz-zio-interop-shared_sjs0.6_2.12/0.5.1'
[error] java.lang.Exception: Failed to close the repository
[error] 	at xerial.sbt.Sonatype$NexusRESTService.closeStage(Sonatype.scala:762)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.closeAndPromote(Sonatype.scala:854)
[error] 	at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeReleaseAll$2(Sonatype.scala:279)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error] 	at scala.collection.immutable.List.map(List.scala:294)
[error] 	at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeReleaseAll$1(Sonatype.scala:278)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.Exception: Failed to close the repository
[error] Use 'last' for the full log.
```

@NeQuissimus Any idea what's going on here?

**Comment by jdegoes** [comment]
Fixed by deleting the staging junk. I don't know why this happened.
