### ISSUE TITLE
Flaky reactive test

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#772]
```
[info] StreamToPublisherTest:
[info] - optional_spec104_mustSignalOnErrorWhenFails *** FAILED ***
[info]   java.lang.RuntimeException: Publisher threw exception (Error-state Publisher scalaz.zio.interop.reactiveStreams.Adapters$$anonfun$streamToPublisher$1$$anonfun$1@22cee1a1 did not call `onError` on new Subscriber within 500 ms) instead of signalling error via onError!
[info]   at org.reactivestreams.tck.PublisherVerification.optional_spec104_mustSignalOnErrorWhenFails(PublisherVerification.java:391)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:498)
[info]   at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
[info]   at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
[info]   at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
[info]   at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
[info]   at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[info]   ...
[info]   Cause: java.lang.AssertionError: Error-state Publisher scalaz.zio.interop.reactiveStreams.Adapters$$anonfun$streamToPublisher$1$$anonfun$1@22cee1a1 did not call `onError` on new Subscriber within 500 ms
[info]   at org.testng.Assert.fail(Assert.java:89)
[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:169)
[info]   at org.reactivestreams.tck.TestEnvironment$Latch.expectClose(TestEnvironment.java:852)
[info]   at org.reactivestreams.tck.TestEnvironment$Latch.expectClose(TestEnvironment.java:846)
[info]   at org.reactivestreams.tck.PublisherVerification$6.run(PublisherVerification.java:381)
[info]   at org.reactivestreams.tck.PublisherVerification.potentiallyPendingTest(PublisherVerification.java:1191)
[info]   at org.reactivestreams.tck.PublisherVerification.whenHasErrorPublisherTest(PublisherVerification.java:1182)
[info]   at org.reactivestreams.tck.PublisherVerification.optional_spec104_mustSignalOnErrorWhenFails(PublisherVerification.java:361)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   ...
```

**Comment by runtologist** [comment]
I'm bike-tripping w/o computer. I'll take a look in a few days, when I'm back.

**Comment by runtologist** [comment]
The TCK catches assertion failures including timeouts and rethrows them with a misleading message. What we see here really are timeouts. The code looks good to me. 

As I cannot reproduce this locally, I guess it is due to slow tests on Travis. I tend to extend the timeout settings for the TCK. 

The timeout can be configured in code (currently 500ms) or via environment variables. The latter would be better I guess, as we could apply it just for Travis.

**Comment by runtologist** [comment]
update: This definitely is a timeout. When I reduce the TCK timeout to a very short setting, I can reproduce.
