### ISSUE TITLE
cats.Monad instance not stack-safe in tailRecM

### ISSUE THREAD

**Issue by ArturGajowy** [scalaz/scalaz-zio#779]
I've successfully replaced `monix.Task` with `zio.Task` in a module test, with one small caveat: I got a StackOverflowError (attached below) in a test supposed to secure against it :)

I've managed to patch it up quickly by overriding the CatsMonad class in my test classpath. You'll notice it does an additional [`ZIO.suspend` around the `f(a)` in trailRecM](https://github.com/ArturGajowy/rchain/commit/79d7c1788877b7ef3df38b96d7643755d2cc4137#diff-c6dba1d615fb8834faafbf313a67d275R13). Without this, I get a SOE.

My intuition for why the SOE happens is: the SOE happens during the construction of the monadic computation, not during evaluation. To prevent that, the construction must be suspended.

This is interesting given that the discipline suite is in place. It seems like it isn't testing against 'lack of stacksafety during computation construction'.

The commit I linked to is everything that was needed to migrate that test to ZIO, including:
 - making the effect type abstract in one test util
 - massaging implicits in other test method to work with abstract F
 - switching out monix.Task for zio.Task in the test class
 - overriding the Monad instance by appropriating the `scalaz.zio.interop` package name a bit ;)

Sorry for not providing an isolated reproduction scenario, that's all I can do for now :)

---

The stacktrace:

```
Exception in thread "zio-default-async-15-1494346128" java.lang.StackOverflowError
	at coop.rchain.rholang.interpreter.Substitute$$anon$7$$Lambda$2670/1955770191.<init>(Unknown Source)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7$$Lambda$2670/1955770191.get$Lambda(Unknown Source)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteNoSort(Substitute.scala:381)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteNoSort(Substitute.scala:275)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.$anonfun$subExp$1(Substitute.scala:129)
	at cats.instances.ListInstances$$anon$1.step$1(list.scala:116)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldM$2(list.scala:121)
	at scalaz.zio.interop.CatsMonad.tailRecM(catsjvm.scala:250)
	at scalaz.zio.interop.CatsMonad.tailRecM(catsjvm.scala:245)
	at cats.instances.ListInstances$$anon$1.foldM(list.scala:121)
	at cats.instances.ListInstances$$anon$1.foldM(list.scala:12)
	at cats.Foldable$Ops.foldM(Foldable.scala:31)
	at cats.Foldable$Ops.foldM$(Foldable.scala:31)
	at cats.Foldable$ToFoldableOps$$anon$6.foldM(Foldable.scala:31)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.subExp(Substitute.scala:122)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.substituteNoSort(Substitute.scala:165)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.substituteNoSort(Substitute.scala:120)
	at coop.rchain.rholang.interpreter.Substitute$.substituteNoSort2(Substitute.scala:58)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.$anonfun$substituteNoSort$36(Substitute.scala:382)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteDelegate(Substitute.scala:295)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteNoSort(Substitute.scala:379)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteNoSort(Substitute.scala:275)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.$anonfun$subExp$1(Substitute.scala:129)
	at cats.instances.ListInstances$$anon$1.step$1(list.scala:116)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldM$2(list.scala:121)
	at scalaz.zio.interop.CatsMonad.tailRecM(catsjvm.scala:250)
	at scalaz.zio.interop.CatsMonad.tailRecM(catsjvm.scala:245)
	at cats.instances.ListInstances$$anon$1.foldM(list.scala:121)
	at cats.instances.ListInstances$$anon$1.foldM(list.scala:12)
	at cats.Foldable$Ops.foldM(Foldable.scala:31)
	at cats.Foldable$Ops.foldM$(Foldable.scala:31)
	at cats.Foldable$ToFoldableOps$$anon$6.foldM(Foldable.scala:31)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.subExp(Substitute.scala:122)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.substituteNoSort(Substitute.scala:165)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.substituteNoSort(Substitute.scala:120)
	at coop.rchain.rholang.interpreter.Substitute$.substituteNoSort2(Substitute.scala:58)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.$anonfun$substituteNoSort$36(Substitute.scala:382)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteDelegate(Substitute.scala:295)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteNoSort(Substitute.scala:379)
	at coop.rchain.rholang.interpreter.Substitute$$anon$7.substituteNoSort(Substitute.scala:275)
	at coop.rchain.rholang.interpreter.Substitute$$anon$2.$anonfun$subExp$1(Substitute.scala:129)
	at cats.instances.ListInstances$$anon$1.step$1(list.scala:116)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldM$2(list.scala:121)
	at scalaz.zio.interop.CatsMonad.tailRecM(catsjvm.scala:250)
	at scalaz.zio.interop.CatsMonad.tailRecM(catsjvm.scala:245)
```

**Comment by kaishh** [comment]
@ArturGajowy Thanks for submitting the issue! Would you have the cycles to submit your changes as a PR too or not this time?

**Comment by ArturGajowy** [comment]
I'll give it a shot next week :)

**Comment by jdegoes** [comment]
> My intuition for why the SOE happens is: the SOE happens during the construction of the monadic computation, not during evaluation. To prevent that, the construction must be suspended.

Yes!

We should definitely fix this.
